apiVersion: v1
kind: Service
metadata:
  name: hello-kenzan
  namespace: auto
  labels:
    name: hello-kenzan
spec:
  type: NodePort
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-kenzan
