apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kazen
  namespace: auto
  labels:
    app: kazen
spec:
  selector:
    matchLabels:
      app: kazen
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kazen
    spec:
      containers:
      - name: kazen
        image: devhub-docker.cisco.com/iot-dockersandbox/gbora/rest-hello-world-fanuc:3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: devhub-docker
